name:  Cypress Test and Docker Build/Push

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.15.0'

      - name: Install dependencies
        run: npm install

      - name: Start the application
        run: npm run dev &
        env:
          CI: true

      - name: Wait for application to be ready
        uses: jakejarvis/wait-action@v0.1.0
        with:
          time: '30' # Adjust this time based on how long your application takes to start

      - name: Run Cypress tests
        run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: cypress-run
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Remove all Docker images
        run: |
          docker rmi $(docker images -qa)

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.USERNAME }}/${{ secrets.DOCKER_REPO }} .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.USERNAME }}/${{ secrets.DOCKER_REPO }}
          
