name: Cypress Test and Docker Build/Push

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Hub build & push
        run : |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker rmi $(docker images -qa)
          pwd
          docker build -t ${{ secrets.USERNAME }}/${{ secrets.DOCKER_REPO }} .
          docker push ${{ secrets.USERNAME }}/${{ secrets.DOCKER_REPO }}
          
        
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_IP_ADDRESS }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            whoami
            
            docker ps -a
            sudo docker stop ${{ secrets.DOCKER_REPO }} || true
            CONTAINER_IDS=$(sudo docker ps -f "ancestor=${{ secrets.USERNAME }}/${{ secrets.DOCKER_REPO }}" --format "{{.ID}}")
            if [ -n "$CONTAINER_IDS" ]; then
            sudo docker rm -f $CONTAINER_IDS
            fi

            docker images
            IMAGE_ID=$(sudo docker images --format "{{.ID}}" ${{ secrets.USERNAME }}/${{ secrets.DOCKER_REPO }})
            echo "Image ID: $IMAGE_ID"
            if [ -n "$IMAGE_ID" ]; then
            sudo docker rmi -f $IMAGE_ID
            echo "Deleted image with ID: $IMAGE_ID"
            else
            echo "No image found for ${{ secrets.USERNAME }}/${{ secrets.DOCKER_REPO }}"
            fi

            sudo docker pull ${{ secrets.USERNAME }}/${{ secrets.DOCKER_REPO }}
            sudo docker ps -a
            sudo ./barreleyescan.sh




