name: Cypress Test and Docker Build/Push

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.15.0'

      - name: Install dependencies
        run: npm install

      - name: Start the application
        run: npm run dev &
        env:
          CI: true

      - name: Wait for application to be ready
        uses: jakejarvis/wait-action@v0.1.0
        with:
          time: '15' # Adjust this time based on how long your application takes to start

      - name: Run Cypress tests
        run: npm run test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Docker Hub build & push
        run : |
          echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker rmi $(docker images -qa)
          docker build -t ${{ secrets.DOCKER_REPO }}:1.0.0 .
          docker images
          docker push ${{ secrets.DOCKER_REPO }}:1.0.0

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP_ADDRESS }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            docker ps -a
            sudo docker stop ${{ secrets.DOCKER_REPO }} || true
            sudo docker rm ${{ secrets.DOCKER_REPO }} || true
            sudo docker pull ${{ secrets.DOCKER_REPO }}:1.0.0
            sudo docker run -d --name ${{ secrets.DOCKER_REPO }} ${{ secrets.DOCKER_REPO }}:1.0.0
            sudo docker ps -a
            sudo chmod +x ./barreleyescan.sh
            sudo ./barreleyescan.sh
            
